version: '3.7'

services:

  pg-postgres:
    image: postgres
    container_name: pg-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgrespwd"
    ports:
      - "5432:5432"
    networks:
      - pg-net        
    restart: always
    privileged: true
    tty: true

  pg-pgadmin4:
    image: dpage/pgadmin4
    container_name: pg-pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "test@test.com"
      PGADMIN_DEFAULT_PASSWORD: "123"
    ports:
    depends_on:
      - pg-postgres
    networks:
      - pg-net    
    links:
      - pg-postgres:deebee      
    restart: always
    privileged: true
    tty: true

  pg-api:
    image: pg-api
    container_name: pg-api
    build:
      context: .
      dockerfile: Dockerfile.external
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DATABASE_CONNECTION_STRING: "Host=deebee;Port=5432;Pooling=true;Database=paymentgateway;User Id=postgres;Password=postgrespwd;"
    ports:
      - "5000:80"
    depends_on:
      - pg-postgres      
    networks:
      - pg-net     
    links:
      - pg-postgres:deebee         
    restart: always
    privileged: true
    tty: true

networks:
  pg-net:
    external: true