version: '3.7'

services:
  
  api-prudential-pruducts-redis:
    image: dtrh.prudentialdobrasil.com.br/dev/redis
    container_name: api-prudential-pruducts-redis
    ports:
      - "6379:6379"
    networks:
      - api-prudential-net        
    restart: always
    privileged: true
    tty: true  

  api-prudential-pruduct-postgres:
    image: dtrh.prudentialdobrasil.com.br/dev/postgres
    container_name: api-prudential-pruducts-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    networks:
      - api-prudential-net        
    restart: always
    privileged: true
    tty: true

networks:
  api-prudential-net:
    external: true